version: '3'

services:

  mysql:
    image: mariadb:10.2.16
    container_name: server
    environment:
      MYSQL_DATABASE: my-database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mysql/data:/var/lib/mysql
    restart: always

  periodic-backup:
    build: ./periodic-backup
    container_name: database-backup
    environment:
      MYSQL_CONTAINER_NAME: server
      MYSQL_DATABASE: my-database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mysql/backup:/opt/mysql/backup
    command: crond -f -d 8
    restart: always
